<?xml version="1.0" encoding="utf-8"?><Database Name="Webdev_Assignment2" Class="DataBaseServerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THINHLAPTOP\SQLEXPRESS;Initial Catalog=Webdev_Assignment2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Webdev_Assignment2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dob" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Licensenumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_Visit" Member="Visits" ThisKey="Id" OtherKey="TreatingDoctor" Type="Visit" />
      <Association Name="Doctor_LabOrder" Member="LabOrders" ThisKey="Id" OtherKey="OrderedDoctor" Type="LabOrder" />
      <Association Name="Doctor_Prescription" Member="Prescriptions" ThisKey="Id" OtherKey="PrescribedDoctor" Type="Prescription" />
    </Type>
  </Table>
  <Table Name="dbo.Visit" Member="Visits">
    <Type Name="Visit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TreatedDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Place" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TreatedPatient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TreatingDoctor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Outcome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabOrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ICDcode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_Visit" Member="Doctor" ThisKey="TreatingDoctor" OtherKey="Id" Type="Doctor" IsForeignKey="true" />
      <Association Name="Hospital_Visit" Member="Hospital" ThisKey="Place" OtherKey="Id" Type="Hospital" IsForeignKey="true" />
      <Association Name="ICD_Visit" Member="ICD" ThisKey="ICDcode" OtherKey="Code" Type="ICD" IsForeignKey="true" />
      <Association Name="LabOrder_Visit" Member="LabOrder" ThisKey="LabOrderId" OtherKey="Id" Type="LabOrder" IsForeignKey="true" />
      <Association Name="Patient_Visit" Member="Patient" ThisKey="TreatedPatient" OtherKey="Id" Type="Patient" IsForeignKey="true" />
      <Association Name="Prescription_Visit" Member="Prescription" ThisKey="PrescriptionId" OtherKey="id" Type="Prescription" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Drug" Member="Drugs">
    <Type Name="Drug">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GenericName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DrugGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DrugGroup_Drug" Member="DrugGroup" ThisKey="DrugGroupId" OtherKey="DrugGroupId" Type="DrugGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DrugGroup" Member="DrugGroups">
    <Type Name="DrugGroup">
      <Column Name="DrugGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="DrugGroup_Drug" Member="Drugs" ThisKey="DrugGroupId" OtherKey="DrugGroupId" Type="Drug" />
    </Type>
  </Table>
  <Table Name="dbo.Hospitals" Member="Hospitals">
    <Type Name="Hospital">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Licensenumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Hospital_Visit" Member="Visits" ThisKey="Id" OtherKey="Place" Type="Visit" />
    </Type>
  </Table>
  <Table Name="dbo.ICD" Member="ICDs">
    <Type Name="ICD">
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ICDChapterId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ICD_Visit" Member="Visits" ThisKey="Code" OtherKey="ICDcode" Type="Visit" />
      <Association Name="ICDChapter_ICD" Member="ICDChapter" ThisKey="ICDChapterId" OtherKey="id" Type="ICDChapter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ICDChapter" Member="ICDChapters">
    <Type Name="ICDChapter">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ICDChapter_ICD" Member="ICDs" ThisKey="id" OtherKey="ICDChapterId" Type="ICD" />
    </Type>
  </Table>
  <Table Name="dbo.LabOrder" Member="LabOrders">
    <Type Name="LabOrder">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderedDoctor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabOrderedDetailsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LabOrder_Visit" Member="Visits" ThisKey="Id" OtherKey="LabOrderId" Type="Visit" />
      <Association Name="Doctor_LabOrder" Member="Doctor" ThisKey="OrderedDoctor" OtherKey="Id" Type="Doctor" IsForeignKey="true" />
      <Association Name="LabOrderDetail_LabOrder" Member="LabOrderDetail" ThisKey="LabOrderedDetailsId" OtherKey="Id" Type="LabOrderDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LabOrderDetails" Member="LabOrderDetails">
    <Type Name="LabOrderDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicalService" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LabOrderDetail_LabOrder" Member="LabOrders" ThisKey="Id" OtherKey="LabOrderedDetailsId" Type="LabOrder" />
      <Association Name="MedicalService_LabOrderDetail" Member="MedicalService1" ThisKey="MedicalService" OtherKey="Id" Type="MedicalService" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalService" Member="MedicalServices">
    <Type Name="MedicalService">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MedicalService_LabOrderDetail" Member="LabOrderDetails" ThisKey="Id" OtherKey="MedicalService" Type="LabOrderDetail" />
      <Association Name="MedicalServiceGroup_MedicalService" Member="MedicalServiceGroup" ThisKey="ServiceGroupId" OtherKey="Id" Type="MedicalServiceGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalServiceGroup" Member="MedicalServiceGroups">
    <Type Name="MedicalServiceGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ServiceGroup" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="MedicalServiceGroup_MedicalService" Member="MedicalServices" ThisKey="Id" OtherKey="ServiceGroupId" Type="MedicalService" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Dob" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Visit" Member="Visits" ThisKey="Id" OtherKey="TreatedPatient" Type="Visit" />
    </Type>
  </Table>
  <Table Name="dbo.Prescription" Member="Prescriptions">
    <Type Name="Prescription">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrescribedDoctor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrescriptionDetailsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Prescription_Visit" Member="Visits" ThisKey="id" OtherKey="PrescriptionId" Type="Visit" />
      <Association Name="Doctor_Prescription" Member="Doctor" ThisKey="PrescribedDoctor" OtherKey="Id" Type="Doctor" IsForeignKey="true" />
      <Association Name="PrescriptionDetail_Prescription" Member="PrescriptionDetail" ThisKey="PrescriptionDetailsId" OtherKey="Id" Type="PrescriptionDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrescriptionDetails" Member="PrescriptionDetails">
    <Type Name="PrescriptionDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DrugId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DosePerDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialInstruction" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="PrescriptionDetail_Prescription" Member="Prescriptions" ThisKey="Id" OtherKey="PrescriptionDetailsId" Type="Prescription" />
    </Type>
  </Table>
</Database>